// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ScraperContext))]
    partial class ScraperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Entities.Person", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DataAccess.Entities.Show", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("DataAccess.Entities.ShowPerson", b =>
                {
                    b.Property<long>("ShowId");

                    b.Property<long>("PersonId");

                    b.HasKey("ShowId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ShowPersons");
                });

            modelBuilder.Entity("DataAccess.Entities.ShowPerson", b =>
                {
                    b.HasOne("DataAccess.Entities.Person", "Person")
                        .WithMany("ShowCasts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataAccess.Entities.Show", "Show")
                        .WithMany("ShowCasts")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
